@startuml

interface StudentActions {
  logout()
  login()
  takeShortBreak()
  takeLongBreak()
}

class Student {
  {static} studentId: Integer
  libraryId: ObjectId
  selectedSeatNumber: Integer
  inputDate: Date
  outputDate: Date
  activeTime: Integer
  breaksUsed: Array[] breaks
  
  logout()
  login()
  takeShortBreak()
  takeLongBreak()
}

class Library {
  {static} libraryId: Integer
  totalCapacity: Integer
  floorsCapacity: Array{} floor
  numberOfTables: Array{} table
  seatsDetails: Array{} seat
  intensity: String

  toAccept()
  cancel()

}

' Student and Library have a association
Student "0..*" - "1..*" Library : association
class Student implements StudentActions

@enduml
